### ISSUE TITLE
Graphmap2 protocol specific alignment

### ISSUE THREAD

**Issue by lwratten** [nf-core/nanoseq#35] opened 2019-11-14 09:30 UTC
In order to enable protocol specific alignment (i.e. `DNA`, `cDNA`, `directRNA` specific), we need to update `graphmap` to `graphmap2` and then implement.

**Comment by drpatelh** [comment] 2019-11-14 09:32
Duplicate of https://github.com/nf-core/nanoseq/issues/25 . Could comment there @lwratten 👍

**Closed by drpatelh** 2019-11-14 09:32 UTC
